const ACTIONTYPES = {
	ALERTON: 'ALERTON',
	ALERTOFF: 'ALERTOFF',
	MUTATECART: 'MUTATECART',
	MUTATECUSTOMERREDUCER: 'MUTATECUSTOMERREDUCER',
	FETCHCUSTOMER: 'FETCHCUSTOMER',
	MUTATEPRODUCT: 'MUTATEPRODUCT',
	MUTATEEXPENSE: 'MUTATEEXPENSE',
	UPDATECUSTOMER: 'UPDATECUSTOMER',
	UPDATEPRODUCT: 'UPDATEPRODUCT',
	MUTATERELOADSTATE: 'MUTATERELOADSTATE',
	MUTATEDASHBOARD: 'MUTATEDASHBOARD',
	FETCHDASHBOARDDATA: 'FETCHDASHBOARDDATA'
}

const API_URL = 'http://ec2-13-232-54-216.ap-south-1.compute.amazonaws.com'

export {ACTIONTYPES, API_URL}