const ACTIONTYPES = {
	ALERTON: 'ALERTON',
	ALERTOFF: 'ALERTOFF',
	MUTATECART: 'MUTATECART',
	MUTATECUSTOMERREDUCER: 'MUTATECUSTOMERREDUCER',
	FETCHCUSTOMER: 'FETCHCUSTOMER'
}

const API_URL = 'http://ec2-13-232-54-216.ap-south-1.compute.amazonaws.com'

export {ACTIONTYPES, API_URL}